name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Unit test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.22.x]
    steps:
    - name: apt update
      run: sudo apt update
    - name: apt upgrade
      run: sudo apt upgrade
    - name: install libsystemd-dev
      run: sudo apt install libsystemd-dev -y
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Run test without integration-test
      run: go test -v -short ./...
